name: Release frontend dev

on:
  push:
    branches:
      - reverse_fix

jobs:

  if: ${{ github.repository == 'Dreyk-Zer0/remna_frontend' }}

  build-and-release:
    name: Build and release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24.19.0'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run start:build

      - name: Create ZIP archive of /dist
        run: |
          zip -r remnawave-frontend.zip ./dist

      - name: Remove previous ZIP from release (if exists)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete-asset dev-build remnawave-frontend.zip || true

      - name: Upload new ZIP to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload dev-build remnawave-frontend.zip --clobber

      - name: Update release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')

          gh release edit dev-build --notes-file - <<EOF
          🔄 Updated development build
          🔗 [Commit]($COMMIT_URL)  
          📅 Built: $DATE
          EOF